# Generated by Django 4.2.6 on 2023-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
