# Generated by Django 4.2.6 on 2023-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicschool', '0002_alter_student_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='instrument',
            field=models.CharField(choices=[('piano', 'piano'), ('violin', 'violin'), ('flute', 'flute'), ('accordion', 'accordion'), ('harp', 'harp')], max_length=255, null=True),
        ),
    ]
