# Generated by Django 4.2.6 on 2023-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicschool', '0003_alter_student_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
